server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/undermoonoldman/springcloud2020_remote_config.git
          search-paths:
            - SpringCloud2020_Remote_Config
      label: master
  #rabbitmq相关配置
  rabbitmq:
    host: gerbil.rmq.cloudamqp.com
    username: erxloiqf
    password: TQpI8_WBzeXn45g0rhnZEobFM36iw6d4
    virtual-host: erxloiqf
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
# rabbitmq相关配置，暴露bus刷新点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'