server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  # 设置feign客户端超时时间(OpenFeign默认支持ribbon)
feign:
  hystrix:
    enabled: true